export const 	GET_ALL_ELEMENTS = 'GET_ALL_ELEMENTS';
export const 	GET_ALL_ELEMENTS_SUCCESS = 'GET_ALL_ELEMENTS_SUCCESS';
export const 	GET_ALL_ELEMENTS_FAILED= 'GET_ALL_ELEMENTS_FAILED';
export const 	GET_ELEMENT_DETAIL= 'GET_ELEMENT_DETAIL';
export const 	GET_ELEMENT_DETAIL_SUCCESS= 'GET_ELEMENT_DETAIL_SUCCESS';
export const 	GET_ELEMENT_DETAIL_FAILED= 'GET_ELEMENT_DETAIL_FAILED';
